
event main {
    // Plusieurs event identiques doivent retourner une erreur !
    /*print("Main");

    
    var label = @Label("Bonjour à tous !");
    label.setPos(50f, 200f);
    label.setAlign(AlignX.right, AlignY.top);*/
    /*label.onSubmit = event(label: Label) {
        "hello".print;
    };*/

    //window.setColor(@Color.white);

    appendUI(@Label("Bonjour !"));

    var sz = 600;
    var btn = @Button;
    btn.setSize(sz, sz);
    //btn.setPos(150f, 200f);
    btn.append(@Label("Bonjour !"));

    var img = @Circle(sz as<float>, true, 2f);
    img.color = @Color.blue;
    btn.addDrawable(img);

    btn.onSubmit = event {
        print("CLICK");
        
        img.filled = !img.filled;
    };
    appendUI(btn);

    /*task(btn: Button) {
        while yield(btn.alive) {
            var msg = <- btn.message;
            switch(msg)
            case(UIMessage.press) {
                print("bouton pressé !");
            }
        }
    }(btn);

    
    task(btn: Button) {
        loop yield {
            var msg = <- btn.message;
            switch(msg)
            case(UIMessage.press) {
                print("bouton pressé !");
            }
            case(UIMessage.kill) {
                die;
            }
        }
    }(btn);*/
    //appendUI(label);


    /*var state = @UIState("hidden");
    state.time = 500;
    state.spline = Spline.sineInOut;
    state.alpha = 0f;
    state.offsetX = -100f;
    state.angle = 45d;
    label.addState(state);

    sleep(1.seconds);
    label.runState("hidden");*/

    loop yield {
        if(isPressed(KeyButton.escape))
            exit;
    }
}