
event main {
    // Plusieurs event identiques doivent retourner une erreur !
    /*print("Main");

    
    var label = @Label("Bonjour à tous !");
    label.setPos(50f, 200f);
    label.setAlign(AlignX.right, AlignY.top);*/
    /*label.onSubmit = event(label: Label) {
        "hello".print;
    };*/

    //window.setColor(@Color.white);

    //appendUI(@Label("Bonjour !"));

    var btn = @FilledButton("Clique ici");
    //btn.setSize(600, 200);

    btn.onSubmit = event {
        print("CLICK");
    };
    appendUI(btn);

    /*task(btn: Button) {
        while yield(btn.alive) {
            var msg = <- btn.message;
            switch(msg)
            case(UIMessage.press) {
                print("bouton pressé !");
            }
        }
    }(btn);

    
    task(btn: Button) {
        loop yield {
            var msg = <- btn.message;
            switch(msg)
            case(UIMessage.press) {
                print("bouton pressé !");
            }
            case(UIMessage.kill) {
                die;
            }
        }
    }(btn);*/
    //appendUI(label);


    /*var state = @UIState("hidden");
    state.time = 500;
    state.spline = Spline.sineInOut;
    state.alpha = 0f;
    state.offsetX = -100f;
    state.angle = 45d;
    label.addState(state);

    sleep(1.seconds);
    label.runState("hidden");*/

    //app.ui.isDebug = true;

    loop yield {
        if(isPressed(KeyButton.escape))
            exit;

        if(isPressed(KeyButton.f1))
            app.ui.isDebug = !app.ui.isDebug;
    }
}